export const queryKeys = {
  dashboardCounts: ['dashboard', 'counts'],
  dashboardCharts: ['dashboard', 'charts'],
  dashboardRecentSales: ['dashboard', 'recent-sales'],
  notifications: (role) => ['notifications', role],
  products: ['products'],
  customers: ['customers'],
  suppliers: ['suppliers'],
  expenses: ['expenses'],
  users: ['users'],
  settings: ['settings'],
  salesOptions: ['sales', 'options'],
  salesHistory: ['sales', 'history'],
  purchasesOptions: ['purchases', 'options'],
  purchasesHistory: ['purchases', 'history'],
  reportsSummary: ['reports', 'summary'],
  customerStatement: (id) => ['customer-statement', id],
  supplierStatement: (id) => ['supplier-statement', id],
};
